# Generated by Django 6.0.4 on 2026-04-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allowance', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remaining_balance', models.FloatField()),
                ('safe_daily_limit', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_res_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allocated_limit', models.FloatField()),
                ('total_spent', models.FloatField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcycle')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pct', models.IntegerField()),
                ('type', models.CharField(choices=[('WARNING_80', 'Warning 80%'), ('EXHAUSTED_100', 'Exhausted 100%')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcycle')),
            ],
        ),
    ]
